name: Run Tests on PR Merge
run-name: runner name ${{github.actor}} 
on:
  pull_request:
    branches: [radheem]

jobs:  
  build:
    name: build-lint check
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        name: Setup Node.js
        with:
          node-version: '21.x'
      - name: Setup yarn and dependencies
        run: npm install -g yarn
      - run: yarn install --immutable
      - run: yarn build

      - name: run linter
        run: yarn lint
      
  test:
    name: test check
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        name: Setup Node.js
        with:
          node-version: '21.x'
          
      - name: Setup yarn and dependencies
        run: npm install -g yarn
      - run: yarn install --immutable
      - run: yarn build
      
      - name: Run unit tests
        run: yarn test:unit
      


  